I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
/esat/spchdisk/scratch/r0797363/venv/ScalableFHVAE/lib/python2.7/site-packages/librosa/__init__.py:35: FutureWarning: You are using librosa with Python 2. Please note that librosa 0.7 will be the last version to support Python 2, after which it will require Python 3 or later.
  FutureWarning)
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: TITAN Xp
major: 6 minor: 1 memoryClockRate (GHz) 1.582
pciBusID 0000:05:00.0
Total memory: 11.91GiB
Free memory: 11.74GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN Xp, pci bus id: 0000:05:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN Xp, pci bus id: 0000:05:00.0)
Traceback (most recent call last):
  File "scripts/eval/run_eval.py", line 73, in <module>
    visualize(exp_dir, step, model, dt_iterator_by_seqs, dt_seqs)
  File "/esat/spchdisk/scratch/r0797363/src/ScalableFHVAE/fhvae/runners/test_fhvae.py", line 99, in visualize
    for x, _, _ , _ , _ in iterator_by_seqs([seq]):
  File "/esat/spchdisk/scratch/r0797363/src/ScalableFHVAE/scripts/eval/eval_loaders.py", line 50, in dt_iterator_by_seqs
    for seqs, feats, nsegs, _, _ in _iterator:
  File "/esat/spchdisk/scratch/r0797363/src/ScalableFHVAE/fhvae/datasets/seg_dataset.py", line 99, in iterator
    for seq_keys, seq_feats, seq_lens, seq_labs, seq_talabs in seq_iterator:
  File "/esat/spchdisk/scratch/r0797363/src/ScalableFHVAE/fhvae/datasets/seq_dataset.py", line 298, in iterator
    feats.append(mapper(self.feats[seq])) # loads the whole file
  File "/esat/spchdisk/scratch/r0797363/src/ScalableFHVAE/fhvae/datasets/seq_dataset.py", line 411, in __getitem__
    with open(self.feats[seq]) as f:
KeyError: 'v60109_0_k'
